// ignore_for_file: always_specify_types
// ignore_for_file: camel_case_types
// ignore_for_file: non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

/// Bindings for `src/rust.h`.
///
/// Regenerate bindings with `dart run ffigen --config ffigen.yaml`.
///
class RustBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  RustBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  void free_error(ffi.Pointer<ffi.Char> error, int error_len) {
    return _free_error(error, error_len);
  }

  late final _free_errorPtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Char>, ffi.Size)>
      >('free_error');
  late final _free_error = _free_errorPtr
      .asFunction<void Function(ffi.Pointer<ffi.Char>, int)>();

  ffi.Pointer<ffi.Void> renderer() {
    return _renderer();
  }

  late final _rendererPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Void> Function()>>('renderer');
  late final _renderer = _rendererPtr
      .asFunction<ffi.Pointer<ffi.Void> Function()>();

  void register_font_family(
    ffi.Pointer<ffi.Void> renderer,
    ffi.Pointer<ffi.Char> family,
    int family_len,
    ffi.Pointer<ffi.Char> data,
    int len,
    ffi.Pointer<ffi.Pointer<ffi.Char>> out_error,
    ffi.Pointer<ffi.Size> out_error_len,
  ) {
    return _register_font_family(
      renderer,
      family,
      family_len,
      data,
      len,
      out_error,
      out_error_len,
    );
  }

  late final _register_font_familyPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<ffi.Char>,
            ffi.Size,
            ffi.Pointer<ffi.Char>,
            ffi.Size,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
            ffi.Pointer<ffi.Size>,
          )
        >
      >('register_font_family');
  late final _register_font_family = _register_font_familyPtr
      .asFunction<
        void Function(
          ffi.Pointer<ffi.Void>,
          ffi.Pointer<ffi.Char>,
          int,
          ffi.Pointer<ffi.Char>,
          int,
          ffi.Pointer<ffi.Pointer<ffi.Char>>,
          ffi.Pointer<ffi.Size>,
        )
      >();

  void register_style(
    ffi.Pointer<ffi.Void> renderer,
    Style style,
    ffi.Pointer<TextStyle> textStyle,
  ) {
    return _register_style(renderer, style.value, textStyle);
  }

  late final _register_stylePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<ffi.Void>,
            ffi.UnsignedInt,
            ffi.Pointer<TextStyle>,
          )
        >
      >('register_style');
  late final _register_style = _register_stylePtr
      .asFunction<
        void Function(ffi.Pointer<ffi.Void>, int, ffi.Pointer<TextStyle>)
      >();

  void serialize_usfm(
    ffi.Pointer<ffi.Char> usfm,
    int usfm_len,
    ffi.Pointer<ffi.Pointer<ffi.Char>> out,
    ffi.Pointer<ffi.Size> out_len,
    ffi.Pointer<ffi.Pointer<ffi.Char>> out_error,
    ffi.Pointer<ffi.Size> out_error_len,
  ) {
    return _serialize_usfm(
      usfm,
      usfm_len,
      out,
      out_len,
      out_error,
      out_error_len,
    );
  }

  late final _serialize_usfmPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<ffi.Char>,
            ffi.Size,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
            ffi.Pointer<ffi.Size>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
            ffi.Pointer<ffi.Size>,
          )
        >
      >('serialize_usfm');
  late final _serialize_usfm = _serialize_usfmPtr
      .asFunction<
        void Function(
          ffi.Pointer<ffi.Char>,
          int,
          ffi.Pointer<ffi.Pointer<ffi.Char>>,
          ffi.Pointer<ffi.Size>,
          ffi.Pointer<ffi.Pointer<ffi.Char>>,
          ffi.Pointer<ffi.Size>,
        )
      >();

  ffi.Pointer<ffi.Void> archived_book(
    ffi.Pointer<ffi.Char> book,
    int book_len,
    ffi.Pointer<ffi.Pointer<ffi.Char>> out_error,
    ffi.Pointer<ffi.Size> out_error_len,
  ) {
    return _archived_book(book, book_len, out_error, out_error_len);
  }

  late final _archived_bookPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Void> Function(
            ffi.Pointer<ffi.Char>,
            ffi.Size,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
            ffi.Pointer<ffi.Size>,
          )
        >
      >('archived_book');
  late final _archived_book = _archived_bookPtr
      .asFunction<
        ffi.Pointer<ffi.Void> Function(
          ffi.Pointer<ffi.Char>,
          int,
          ffi.Pointer<ffi.Pointer<ffi.Char>>,
          ffi.Pointer<ffi.Size>,
        )
      >();

  void book_identifier(
    ffi.Pointer<ffi.Void> usfm,
    ffi.Pointer<ffi.Pointer<ffi.Char>> out,
    ffi.Pointer<ffi.Size> out_len,
    ffi.Pointer<ffi.Pointer<ffi.Char>> out_error,
    ffi.Pointer<ffi.Size> out_error_len,
  ) {
    return _book_identifier(usfm, out, out_len, out_error, out_error_len);
  }

  late final _book_identifierPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
            ffi.Pointer<ffi.Size>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
            ffi.Pointer<ffi.Size>,
          )
        >
      >('book_identifier');
  late final _book_identifier = _book_identifierPtr
      .asFunction<
        void Function(
          ffi.Pointer<ffi.Void>,
          ffi.Pointer<ffi.Pointer<ffi.Char>>,
          ffi.Pointer<ffi.Size>,
          ffi.Pointer<ffi.Pointer<ffi.Char>>,
          ffi.Pointer<ffi.Size>,
        )
      >();

  ffi.Pointer<ffi.Void> layout(
    ffi.Pointer<ffi.Void> renderer,
    ffi.Pointer<ffi.Void> usfm,
    ffi.Pointer<Dimensions> dim,
    ffi.Pointer<ffi.Pointer<ffi.Char>> out_error,
    ffi.Pointer<ffi.Size> out_error_len,
  ) {
    return _layout(renderer, usfm, dim, out_error, out_error_len);
  }

  late final _layoutPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Void> Function(
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<Dimensions>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
            ffi.Pointer<ffi.Size>,
          )
        >
      >('layout');
  late final _layout = _layoutPtr
      .asFunction<
        ffi.Pointer<ffi.Void> Function(
          ffi.Pointer<ffi.Void>,
          ffi.Pointer<ffi.Void>,
          ffi.Pointer<Dimensions>,
          ffi.Pointer<ffi.Pointer<ffi.Char>>,
          ffi.Pointer<ffi.Size>,
        )
      >();

  void serialize_pages(
    ffi.Pointer<ffi.Void> painter,
    ffi.Pointer<ffi.Pointer<ffi.Char>> out,
    ffi.Pointer<ffi.Size> out_len,
    ffi.Pointer<ffi.Pointer<ffi.Char>> out_error,
    ffi.Pointer<ffi.Size> out_error_len,
  ) {
    return _serialize_pages(painter, out, out_len, out_error, out_error_len);
  }

  late final _serialize_pagesPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
            ffi.Pointer<ffi.Size>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
            ffi.Pointer<ffi.Size>,
          )
        >
      >('serialize_pages');
  late final _serialize_pages = _serialize_pagesPtr
      .asFunction<
        void Function(
          ffi.Pointer<ffi.Void>,
          ffi.Pointer<ffi.Pointer<ffi.Char>>,
          ffi.Pointer<ffi.Size>,
          ffi.Pointer<ffi.Pointer<ffi.Char>>,
          ffi.Pointer<ffi.Size>,
        )
      >();

  ffi.Pointer<ffi.Void> archived_pages(
    ffi.Pointer<ffi.Char> pages,
    int pages_len,
    ffi.Pointer<ffi.Pointer<ffi.Char>> out_error,
    ffi.Pointer<ffi.Size> out_error_len,
  ) {
    return _archived_pages(pages, pages_len, out_error, out_error_len);
  }

  late final _archived_pagesPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Void> Function(
            ffi.Pointer<ffi.Char>,
            ffi.Size,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
            ffi.Pointer<ffi.Size>,
          )
        >
      >('archived_pages');
  late final _archived_pages = _archived_pagesPtr
      .asFunction<
        ffi.Pointer<ffi.Void> Function(
          ffi.Pointer<ffi.Char>,
          int,
          ffi.Pointer<ffi.Pointer<ffi.Char>>,
          ffi.Pointer<ffi.Size>,
        )
      >();

  int num_pages(ffi.Pointer<ffi.Void> archived_pages) {
    return _num_pages(archived_pages);
  }

  late final _num_pagesPtr =
      _lookup<ffi.NativeFunction<ffi.Size Function(ffi.Pointer<ffi.Void>)>>(
        'num_pages',
      );
  late final _num_pages = _num_pagesPtr
      .asFunction<int Function(ffi.Pointer<ffi.Void>)>();

  void page(
    ffi.Pointer<ffi.Void> renderer,
    ffi.Pointer<ffi.Void> archived_pages,
    int n,
    ffi.Pointer<ffi.Pointer<Text>> out,
    ffi.Pointer<ffi.Size> out_len,
    ffi.Pointer<ffi.Pointer<ffi.Char>> out_error,
    ffi.Pointer<ffi.Size> out_error_len,
  ) {
    return _page(
      renderer,
      archived_pages,
      n,
      out,
      out_len,
      out_error,
      out_error_len,
    );
  }

  late final _pagePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<ffi.Void>,
            ffi.Size,
            ffi.Pointer<ffi.Pointer<Text>>,
            ffi.Pointer<ffi.Size>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
            ffi.Pointer<ffi.Size>,
          )
        >
      >('page');
  late final _page = _pagePtr
      .asFunction<
        void Function(
          ffi.Pointer<ffi.Void>,
          ffi.Pointer<ffi.Void>,
          int,
          ffi.Pointer<ffi.Pointer<Text>>,
          ffi.Pointer<ffi.Size>,
          ffi.Pointer<ffi.Pointer<ffi.Char>>,
          ffi.Pointer<ffi.Size>,
        )
      >();

  void serialize_indices(
    ffi.Pointer<ffi.Void> painter,
    ffi.Pointer<ffi.Pointer<ffi.Char>> out,
    ffi.Pointer<ffi.Size> out_len,
    ffi.Pointer<ffi.Pointer<ffi.Char>> out_error,
    ffi.Pointer<ffi.Size> out_error_len,
  ) {
    return _serialize_indices(painter, out, out_len, out_error, out_error_len);
  }

  late final _serialize_indicesPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
            ffi.Pointer<ffi.Size>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
            ffi.Pointer<ffi.Size>,
          )
        >
      >('serialize_indices');
  late final _serialize_indices = _serialize_indicesPtr
      .asFunction<
        void Function(
          ffi.Pointer<ffi.Void>,
          ffi.Pointer<ffi.Pointer<ffi.Char>>,
          ffi.Pointer<ffi.Size>,
          ffi.Pointer<ffi.Pointer<ffi.Char>>,
          ffi.Pointer<ffi.Size>,
        )
      >();

  void serialize_verses(
    ffi.Pointer<ffi.Void> painter,
    ffi.Pointer<ffi.Pointer<ffi.Char>> out,
    ffi.Pointer<ffi.Size> out_len,
    ffi.Pointer<ffi.Pointer<ffi.Char>> out_error,
    ffi.Pointer<ffi.Size> out_error_len,
  ) {
    return _serialize_verses(painter, out, out_len, out_error, out_error_len);
  }

  late final _serialize_versesPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
            ffi.Pointer<ffi.Size>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
            ffi.Pointer<ffi.Size>,
          )
        >
      >('serialize_verses');
  late final _serialize_verses = _serialize_versesPtr
      .asFunction<
        void Function(
          ffi.Pointer<ffi.Void>,
          ffi.Pointer<ffi.Pointer<ffi.Char>>,
          ffi.Pointer<ffi.Size>,
          ffi.Pointer<ffi.Pointer<ffi.Char>>,
          ffi.Pointer<ffi.Size>,
        )
      >();

  void serialize_verse_ranges(
    ffi.Pointer<ffi.Void> painter,
    ffi.Pointer<ffi.Pointer<ffi.Char>> out,
    ffi.Pointer<ffi.Size> out_len,
  ) {
    return _serialize_verse_ranges(painter, out, out_len);
  }

  late final _serialize_verse_rangesPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
            ffi.Pointer<ffi.Size>,
          )
        >
      >('serialize_verse_ranges');
  late final _serialize_verse_ranges = _serialize_verse_rangesPtr
      .asFunction<
        void Function(
          ffi.Pointer<ffi.Void>,
          ffi.Pointer<ffi.Pointer<ffi.Char>>,
          ffi.Pointer<ffi.Size>,
        )
      >();

  ffi.Pointer<ffi.Void> load_search_engine(
    ffi.Pointer<ffi.Char> model,
    int model_len,
    ffi.Pointer<ffi.Char> tokenizer,
    int tokenizer_len,
    ffi.Pointer<ffi.Char> hnsw_dir,
    int hnsw_dir_len,
    ffi.Pointer<ffi.Char> hnsw_basename,
    int hnsw_basename_len,
    ffi.Pointer<ffi.Char> idx,
    int idx_len,
    ffi.Pointer<ffi.Pointer<ffi.Char>> out_error,
    ffi.Pointer<ffi.Size> out_error_len,
  ) {
    return _load_search_engine(
      model,
      model_len,
      tokenizer,
      tokenizer_len,
      hnsw_dir,
      hnsw_dir_len,
      hnsw_basename,
      hnsw_basename_len,
      idx,
      idx_len,
      out_error,
      out_error_len,
    );
  }

  late final _load_search_enginePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Void> Function(
            ffi.Pointer<ffi.Char>,
            ffi.Size,
            ffi.Pointer<ffi.Char>,
            ffi.Size,
            ffi.Pointer<ffi.Char>,
            ffi.Size,
            ffi.Pointer<ffi.Char>,
            ffi.Size,
            ffi.Pointer<ffi.Char>,
            ffi.Size,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
            ffi.Pointer<ffi.Size>,
          )
        >
      >('load_search_engine');
  late final _load_search_engine = _load_search_enginePtr
      .asFunction<
        ffi.Pointer<ffi.Void> Function(
          ffi.Pointer<ffi.Char>,
          int,
          ffi.Pointer<ffi.Char>,
          int,
          ffi.Pointer<ffi.Char>,
          int,
          ffi.Pointer<ffi.Char>,
          int,
          ffi.Pointer<ffi.Char>,
          int,
          ffi.Pointer<ffi.Pointer<ffi.Char>>,
          ffi.Pointer<ffi.Size>,
        )
      >();

  void search(
    ffi.Pointer<ffi.Void> engine,
    ffi.Pointer<ffi.Char> query,
    int query_len,
    int top_k,
    int ef,
    ffi.Pointer<ffi.Pointer<ffi.Size>> out_ids,
    ffi.Pointer<ffi.Pointer<ffi.Float>> out_distances,
    ffi.Pointer<ffi.Size> out_len,
    ffi.Pointer<ffi.Pointer<ffi.Char>> out_error,
    ffi.Pointer<ffi.Size> out_error_len,
  ) {
    return _search(
      engine,
      query,
      query_len,
      top_k,
      ef,
      out_ids,
      out_distances,
      out_len,
      out_error,
      out_error_len,
    );
  }

  late final _searchPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<ffi.Char>,
            ffi.Size,
            ffi.Size,
            ffi.Size,
            ffi.Pointer<ffi.Pointer<ffi.Size>>,
            ffi.Pointer<ffi.Pointer<ffi.Float>>,
            ffi.Pointer<ffi.Size>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
            ffi.Pointer<ffi.Size>,
          )
        >
      >('search');
  late final _search = _searchPtr
      .asFunction<
        void Function(
          ffi.Pointer<ffi.Void>,
          ffi.Pointer<ffi.Char>,
          int,
          int,
          int,
          ffi.Pointer<ffi.Pointer<ffi.Size>>,
          ffi.Pointer<ffi.Pointer<ffi.Float>>,
          ffi.Pointer<ffi.Size>,
          ffi.Pointer<ffi.Pointer<ffi.Char>>,
          ffi.Pointer<ffi.Size>,
        )
      >();

  void get_search_result(
    ffi.Pointer<ffi.Void> engine,
    ffi.Pointer<ffi.Void> ref_index,
    int id,
    ffi.Pointer<ffi.Size> out_page,
    ffi.Pointer<ffi.Pointer<ffi.Char>> out_book,
    ffi.Pointer<ffi.Size> out_book_len,
    ffi.Pointer<ffi.Pointer<ffi.Char>> out_header,
    ffi.Pointer<ffi.Size> out_header_len,
    ffi.Pointer<ffi.UnsignedShort> out_chapter,
    ffi.Pointer<ffi.UnsignedShort> out_verse,
    ffi.Pointer<ffi.Pointer<ffi.Char>> out_error,
    ffi.Pointer<ffi.Size> out_error_len,
  ) {
    return _get_search_result(
      engine,
      ref_index,
      id,
      out_page,
      out_book,
      out_book_len,
      out_header,
      out_header_len,
      out_chapter,
      out_verse,
      out_error,
      out_error_len,
    );
  }

  late final _get_search_resultPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<ffi.Void>,
            ffi.Size,
            ffi.Pointer<ffi.Size>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
            ffi.Pointer<ffi.Size>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
            ffi.Pointer<ffi.Size>,
            ffi.Pointer<ffi.UnsignedShort>,
            ffi.Pointer<ffi.UnsignedShort>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
            ffi.Pointer<ffi.Size>,
          )
        >
      >('get_search_result');
  late final _get_search_result = _get_search_resultPtr
      .asFunction<
        void Function(
          ffi.Pointer<ffi.Void>,
          ffi.Pointer<ffi.Void>,
          int,
          ffi.Pointer<ffi.Size>,
          ffi.Pointer<ffi.Pointer<ffi.Char>>,
          ffi.Pointer<ffi.Size>,
          ffi.Pointer<ffi.Pointer<ffi.Char>>,
          ffi.Pointer<ffi.Size>,
          ffi.Pointer<ffi.UnsignedShort>,
          ffi.Pointer<ffi.UnsignedShort>,
          ffi.Pointer<ffi.Pointer<ffi.Char>>,
          ffi.Pointer<ffi.Size>,
        )
      >();

  ffi.Pointer<ffi.Void> ref_index_builder_new() {
    return _ref_index_builder_new();
  }

  late final _ref_index_builder_newPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Void> Function()>>(
        'ref_index_builder_new',
      );
  late final _ref_index_builder_new = _ref_index_builder_newPtr
      .asFunction<ffi.Pointer<ffi.Void> Function()>();

  void ref_index_builder_add(
    ffi.Pointer<ffi.Void> builder,
    ffi.Pointer<ffi.Char> data,
    int data_len,
    ffi.Pointer<ffi.Pointer<ffi.Char>> out_error,
    ffi.Pointer<ffi.Size> out_error_len,
  ) {
    return _ref_index_builder_add(
      builder,
      data,
      data_len,
      out_error,
      out_error_len,
    );
  }

  late final _ref_index_builder_addPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<ffi.Char>,
            ffi.Size,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
            ffi.Pointer<ffi.Size>,
          )
        >
      >('ref_index_builder_add');
  late final _ref_index_builder_add = _ref_index_builder_addPtr
      .asFunction<
        void Function(
          ffi.Pointer<ffi.Void>,
          ffi.Pointer<ffi.Char>,
          int,
          ffi.Pointer<ffi.Pointer<ffi.Char>>,
          ffi.Pointer<ffi.Size>,
        )
      >();

  ffi.Pointer<ffi.Void> ref_index_builder_finish(
    ffi.Pointer<ffi.Void> builder,
    ffi.Pointer<ffi.Pointer<ffi.Char>> out_error,
    ffi.Pointer<ffi.Size> out_error_len,
  ) {
    return _ref_index_builder_finish(builder, out_error, out_error_len);
  }

  late final _ref_index_builder_finishPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Void> Function(
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
            ffi.Pointer<ffi.Size>,
          )
        >
      >('ref_index_builder_finish');
  late final _ref_index_builder_finish = _ref_index_builder_finishPtr
      .asFunction<
        ffi.Pointer<ffi.Void> Function(
          ffi.Pointer<ffi.Void>,
          ffi.Pointer<ffi.Pointer<ffi.Char>>,
          ffi.Pointer<ffi.Size>,
        )
      >();

  void ref_index_free(ffi.Pointer<ffi.Void> index) {
    return _ref_index_free(index);
  }

  late final _ref_index_freePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'ref_index_free',
      );
  late final _ref_index_free = _ref_index_freePtr
      .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void ref_index_lookup(
    ffi.Pointer<ffi.Void> index,
    ffi.Pointer<ffi.Char> query,
    int query_len,
    int limit,
    ffi.Pointer<ffi.Pointer<RefHit>> out,
    ffi.Pointer<ffi.Size> out_len,
    ffi.Pointer<ffi.Pointer<ffi.Char>> out_error,
    ffi.Pointer<ffi.Size> out_error_len,
  ) {
    return _ref_index_lookup(
      index,
      query,
      query_len,
      limit,
      out,
      out_len,
      out_error,
      out_error_len,
    );
  }

  late final _ref_index_lookupPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<ffi.Char>,
            ffi.Size,
            ffi.Size,
            ffi.Pointer<ffi.Pointer<RefHit>>,
            ffi.Pointer<ffi.Size>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
            ffi.Pointer<ffi.Size>,
          )
        >
      >('ref_index_lookup');
  late final _ref_index_lookup = _ref_index_lookupPtr
      .asFunction<
        void Function(
          ffi.Pointer<ffi.Void>,
          ffi.Pointer<ffi.Char>,
          int,
          int,
          ffi.Pointer<ffi.Pointer<RefHit>>,
          ffi.Pointer<ffi.Size>,
          ffi.Pointer<ffi.Pointer<ffi.Char>>,
          ffi.Pointer<ffi.Size>,
        )
      >();

  void ref_hits_free(ffi.Pointer<RefHit> hits, int len) {
    return _ref_hits_free(hits, len);
  }

  late final _ref_hits_freePtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<RefHit>, ffi.Size)>
      >('ref_hits_free');
  late final _ref_hits_free = _ref_hits_freePtr
      .asFunction<void Function(ffi.Pointer<RefHit>, int)>();

  void indices_book_title(
    ffi.Pointer<ffi.Char> data,
    int data_len,
    ffi.Pointer<ffi.Pointer<ffi.Char>> out,
    ffi.Pointer<ffi.Size> out_len,
    ffi.Pointer<ffi.Pointer<ffi.Char>> out_error,
    ffi.Pointer<ffi.Size> out_error_len,
  ) {
    return _indices_book_title(
      data,
      data_len,
      out,
      out_len,
      out_error,
      out_error_len,
    );
  }

  late final _indices_book_titlePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<ffi.Char>,
            ffi.Size,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
            ffi.Pointer<ffi.Size>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
            ffi.Pointer<ffi.Size>,
          )
        >
      >('indices_book_title');
  late final _indices_book_title = _indices_book_titlePtr
      .asFunction<
        void Function(
          ffi.Pointer<ffi.Char>,
          int,
          ffi.Pointer<ffi.Pointer<ffi.Char>>,
          ffi.Pointer<ffi.Size>,
          ffi.Pointer<ffi.Pointer<ffi.Char>>,
          ffi.Pointer<ffi.Size>,
        )
      >();
}

final class TextStyle extends ffi.Struct {
  external ffi.Pointer<ffi.Char> font_family;

  @ffi.Size()
  external int font_family_len;

  @ffi.Float()
  external double font_size;

  @ffi.Float()
  external double height;

  @ffi.Float()
  external double letter_spacing;

  @ffi.Float()
  external double word_spacing;

  @ffi.Int()
  external int underline;
}

enum Style {
  VERSE(0),
  NORMAL(1),
  HEADER(2),
  CHAPTER(3),
  WORD(4),
  CALLER(9),
  FOOTNOTE(10),
  CROSSREF(11);

  final int value;
  const Style(this.value);

  static Style fromValue(int value) => switch (value) {
    0 => VERSE,
    1 => NORMAL,
    2 => HEADER,
    3 => CHAPTER,
    4 => WORD,
    9 => CALLER,
    10 => FOOTNOTE,
    11 => CROSSREF,
    _ => throw ArgumentError("Unknown value for Style: $value"),
  };
}

final class Rectangle extends ffi.Struct {
  @ffi.Float()
  external double top;

  @ffi.Float()
  external double left;

  @ffi.Float()
  external double width;

  @ffi.Float()
  external double height;
}

final class Text extends ffi.Struct {
  external ffi.Pointer<ffi.Char> text;

  @ffi.Size()
  external int len;

  external Rectangle rect;

  external TextStyle style;
}

final class Dimensions extends ffi.Struct {
  @ffi.Float()
  external double width;

  @ffi.Float()
  external double height;

  @ffi.Float()
  external double header_height;

  @ffi.Float()
  external double drop_cap_padding;
}

/// One reference-search hit. `book` and `header` point into the RefIndex that
/// produced the hit and stay valid for as long as it lives; only the array
/// itself needs freeing, via ref_hits_free.
/// A `chapter` or `verse` of 0 means the hit stops at the level above: a book
/// hit carries neither, a chapter hit carries only a chapter.
final class RefHit extends ffi.Struct {
  @ffi.Size()
  external int page;

  external ffi.Pointer<ffi.Char> book;

  @ffi.Size()
  external int book_len;

  external ffi.Pointer<ffi.Char> header;

  @ffi.Size()
  external int header_len;

  @ffi.UnsignedShort()
  external int chapter;

  @ffi.UnsignedShort()
  external int verse;
}
