name: Release Asset
permissions:
  contents: write
on:
  push:
    tags:
      - "asset-*"
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: "**/*.zip"
